fixed ggshield: command not found

diff --git a/.github/workflows/gitguardian-scan.yml b/.github/workflows/gitguardian-scan.yml
--- a/.github/workflows/gitguardian-scan.yml
+++ b/.github/workflows/gitguardian-scan.yml
@@ -1,31 +1,30 @@
-name: Scan GitHub Repositories for Secrets
+name: GitHub Profile Scanner
 
 on:
-  workflow_dispatch:
-  schedule:
-    - cron: "0 0 * * *"
+  push:
+    branches:
+      - main  # Change this to the branch name you are working with
 
 jobs:
   scan:
     runs-on: ubuntu-latest
 
     steps:
-    - name: Checkout repository
+    - name: Checkout code
       uses: actions/checkout@v3
 
     - name: Send start message to Discord
       run: |
-        curl -H "Content-Type: application/json" -X POST -d "{\"content\": \"**Scan Started**: The GitHub repository scan process has started.\"}" ${{ secrets.DISCORD_WEBHOOK }}
+        curl -H "Content-Type: application/json" \
+             -X POST \
+             -d "{\"content\": \"**Scan Started**: The GitHub profile scan process has started.\"}" \
+             ${{ secrets.DISCORD_WEBHOOK }}
 
     - name: Install GitGuardian CLI
       run: |
         pip install ggshield
 
-    - name: Sort GitHub usernames and remove duplicates
-      run: |
-        sort github_username.txt | uniq > sorted_usernames.txt
-
-    - name: Retrieve repositories for each username and scan for secrets
+    - name: Scan GitHub Profiles
       run: |
         while read username; do
           repos=$(curl -s https://api.github.com/users/$username/repos | jq -r '.[].clone_url')
@@ -33,30 +32,42 @@ jobs:
             echo "$repos" > ${username}_repos.txt
           else
             echo "No repositories found for $username" >> error.log
-            curl -H "Content-Type: application/json" -X POST -d "{\"content\": \"> **Error**: No repositories found for \`github.com/$username\`\"}" ${{ secrets.DISCORD_WEBHOOK }}
+            curl -H "Content-Type: application/json" \
+                 -X POST \
+                 -d "{\"content\": \"> **Error**: No repositories found for ```github.com/$username```\"}" \
+                 ${{ secrets.DISCORD_WEBHOOK }}
           fi
           sleep 1  # Add delay to prevent rate limiting
-        done < sorted_usernames.txt
+        done < github_username.txt
 
-    - name: Clone repositories and run GitGuardian scan
+    - name: Clone and Scan Repositories
       run: |
         while read username; do
           mkdir -p repos/$username
           cd repos/$username
           if [ -f ../../${username}_repos.txt ]; then
             while read repo; do
-              git clone $repo || { echo "Failed to clone $repo" >> error.log; continue; }
+              git clone $repo || { echo "Failed to clone $repo" >> ../../error.log; continue; }
             done < ../../${username}_repos.txt
             ggshield secret scan .
             scan_status=$?
             cd ../../
             if [ $scan_status -eq 0 ]; then
-              curl -H "Content-Type: application/json" -X POST -d "{\"content\": \"> **Scan Completed Successfully**\n> \`github.com/$username\` Scan Passed and Action Succeeded\"}" ${{ secrets.DISCORD_WEBHOOK }}
+              curl -H "Content-Type: application/json" \
+                   -X POST \
+                   -d "{\"content\": \"> **Scan Completed Successfully**\n> ```github.com/$username Scan Passed and Action Succeeded```\"}" \
+                   ${{ secrets.DISCORD_WEBHOOK }}
             else
-              curl -H "Content-Type: application/json" -X POST -d "{\"content\": \"> **Scan Completed with Issues**\n> \`github.com/$username\` Scan Failed and Action Failed\"}" ${{ secrets.DISCORD_WEBHOOK }}
+              curl -H "Content-Type: application/json" \
+                   -X POST \
+                   -d "{\"content\": \"> **Scan Completed with Issues**\n> ```github.com/$username Scan Failed and Action Failed```\"}" \
+                   ${{ secrets.DISCORD_WEBHOOK }}
             fi
           else
-            curl -H "Content-Type: application/json" -X POST -d "{\"content\": \"> **Error**: No repositories to scan..! for \`github.com/$username\`\"}" ${{ secrets.DISCORD_WEBHOOK }}
+            curl -H "Content-Type: application/json" \
+                 -X POST \
+                 -d "{\"content\": \"> **Error**: No repositories to scan for ```github.com/$username```\"}" \
+                 ${{ secrets.DISCORD_WEBHOOK }}
           fi
           sleep 1  # Add delay to prevent rate limiting
-        done < sorted_usernames.txt
+        done < github_username.txt
