updated webhookk to action

diff --git a/.github/workflows/gitguardian-scan.yml b/.github/workflows/gitguardian-scan.yml
--- a/.github/workflows/gitguardian-scan.yml
+++ b/.github/workflows/gitguardian-scan.yml
@@ -1,64 +1,66 @@
-name: Scan GitHub Profiles for Secrets
+name: GitGuardian Scanner
 
 on:
   push:
     branches:
       - main
+  workflow_dispatch:
 
 jobs:
   scan:
     runs-on: ubuntu-latest
     steps:
-    - name: Checkout repository
-      uses: actions/checkout@v3
+      - name: Checkout repository
+        uses: actions/checkout@v3
 
-    - name: Send start message to Discord
-      run: |
-        curl -H "Content-Type: application/json" -X POST -d "{\"content\": \"**Scan Started**: The GitHub profile scan process has started.\"}" YOUR_DISCORD_WEBHOOK_URL
+      - name: Send start message to Discord
+        run: |
+          curl -H "Content-Type: application/json" -X POST -d "{\"content\": \"**Scan Started**: The GitHub profile scan process has started.\"}" https://discord.com/api/webhooks/1277716500030947398/JinsvG3G3Rjvr-XkZEBFF8P6L4suKqh7NWj8b5Q2aW-hDgc7_dhKN7YvLeeZcW4ysJA1
 
-    - name: Install dependencies
-      run: |
-        sudo apt-get update
-        sudo apt-get install -y jq curl
+      - name: Install dependencies
+        run: |
+          sudo apt-get update
+          sudo apt-get install -y jq curl
 
-    - name: Process GitHub usernames
-      run: |
-        sort github_username.txt | uniq > sorted_usernames.txt
-        while read username; do
-          repos=$(curl -s https://api.github.com/users/$username/repos | jq -r '.[].clone_url')
-          if [ -n "$repos" ]; then
-            echo "$repos" > ${username}_repos.txt
-          else
-            echo "No repositories found for $username" >> error.log
-            curl -H "Content-Type: application/json" -X POST -d "{\"content\": \"> **Error**: No repositories found for ```github.com/$username```\"}" YOUR_DISCORD_WEBHOOK_URL
-          fi
-          sleep 1  # Add delay to prevent rate limiting
-        done < sorted_usernames.txt
-
-    - name: Clone Repositories and Scan for Secrets
-      run: |
-        while read username; do
-          mkdir -p repos/$username
-          cd repos/$username
-          if [ -f ../../${username}_repos.txt ]; then
-            while read repo; do
-              git clone $repo || { echo "Failed to clone $repo" >> ../../error.log; continue; }
-            done < ../../${username}_repos.txt
-            ggshield secret scan .
-            scan_status=$?
-            cd ../../
-            if [ $scan_status -eq 0 ]; then
-              curl -H "Content-Type: application/json" -X POST -d "{\"content\": \"> **Scan Completed Successfully**\n> ```github.com/$username Scan Passed and Action Succeeded```\"}" YOUR_DISCORD_WEBHOOK_URL
+      - name: Read GitHub usernames and get repositories
+        run: |
+          sort github_username.txt | uniq > sorted_usernames.txt
+          while read username; do
+            repos=$(curl -s https://api.github.com/users/$username/repos | jq -r '.[].clone_url')
+            if [ -n "$repos" ]; then
+              echo "$repos" > ${username}_repos.txt
             else
-              curl -H "Content-Type: application/json" -X POST -d "{\"content\": \"> **Scan Completed with Issues**\n> ```github.com/$username Scan Failed and Action Failed```\"}" YOUR_DISCORD_WEBHOOK_URL
+              echo "No repositories found for $username" >> error.log
+              curl -H "Content-Type: application/json" -X POST -d "{\"content\": \"> **Error**: No repositories found for ```github.com/$username```\"}" https://discord.com/api/webhooks/1277716500030947398/JinsvG3G3Rjvr-XkZEBFF8P6L4suKqh7NWj8b5Q2aW-hDgc7_dhKN7YvLeeZcW4ysJA1
             fi
-          else
-            curl -H "Content-Type: application/json" -X POST -d "{\"content\": \"> **Error**: No repositories to scan for ```github.com/$username```\"}" YOUR_DISCORD_WEBHOOK_URL
-          fi
-          sleep 1  # Add delay to prevent rate limiting
-        done < sorted_usernames.txt
+            sleep 1  # Add delay to prevent rate limiting
+          done < sorted_usernames.txt
 
-    - name: Cleanup
-      run: |
-        rm -rf repos
-        rm -f *.txt
+      - name: Clone repositories and scan for secrets
+        run: |
+          while read username; do
+            mkdir -p repos/$username
+            cd repos/$username
+            if [ -f ../../${username}_repos.txt ]; then
+              while read repo; do
+                git clone $repo || { echo "Failed to clone $repo" >> ../../error.log; continue; }
+              done < ../../${username}_repos.txt
+              ggshield secret scan .
+              scan_status=$?
+              cd ../../
+              if [ $scan_status -eq 0 ]; then
+                curl -H "Content-Type: application/json" -X POST -d "{\"content\": \"> **Scan Completed Successfully**\n> ```github.com/$username Scan Passed and Action Succeeded```\"}" https://discord.com/api/webhooks/1277716500030947398/JinsvG3G3Rjvr-XkZEBFF8P6L4suKqh7NWj8b5Q2aW-hDgc7_dhKN7YvLeeZcW4ysJA1
+              else
+                curl -H "Content-Type: application/json" -X POST -d "{\"content\": \"> **Scan Completed with Issues**\n> ```github.com/$username Scan Failed and Action Failed```\"}" https://discord.com/api/webhooks/1277716500030947398/JinsvG3G3Rjvr-XkZEBFF8P6L4suKqh7NWj8b5Q2aW-hDgc7_dhKN7YvLeeZcW4ysJA1
+              fi
+            else
+              curl -H "Content-Type: application/json" -X POST -d "{\"content\": \"> **Error**: No repositories to scan for ```github.com/$username```\"}" https://discord.com/api/webhooks/1277716500030947398/JinsvG3G3Rjvr-XkZEBFF8P6L4suKqh7NWj8b5Q2aW-hDgc7_dhKN7YvLeeZcW4ysJA1
+            fi
+            sleep 1  # Add delay to prevent rate limiting
+          done < sorted_usernames.txt
+
+      - name: Cleanup
+        run: |
+          rm -rf repos
+          rm sorted_usernames.txt
+          rm *_repos.txt
